### ISSUE TITLE
当我测试时，如下错误

### ISSUE THREAD

**Issue by XABxab123** [Wenretium/CIPGAN#1]
当我测试时，如下错误：FileNotFoundError: [Errno 2] No such file or directory: './checkpoints/CIP_dataset1/latest_net_G.pth'
请问大佬如何解决

**Comment by Wenretium** [comment]
你好！我这个项目基于[pytorch-CycleGAN-and-pix2pix](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix)的代码框架，训练的模型结果和可视化结果会存到checkpoints这个文件夹下。这个文件夹实在太大了（屡次迭代的模型+中间图像），所以我没有一并上传。我训练好的模型结果放在`demo_files/models/`路径下，你可以运行我写的gui.py文件直接进行inference。如果你想要使用test.py进行测试，需要创建'`./checkpoints/CIP_dataset1/`这个路径，然后把我`demo_files/models/`下的模型文件移过去这个路径下，并更名为latest_net_G.pth（想试哪个模型就改哪个，如果你熟悉原项目结构，应该很简单）。

**Comment by Wenretium** [comment]
如果test使用的模型是`dataset1_vgg_atten4_G_A`这个，需要在命令行后面加上 --self_attention --self_attention_thresh 0.8(可以自己改变参数)

**Comment by huahuabai** [comment]
直接进行测试，demo_files/下面并没有生成result文件夹，当我新建result文件夹之后，并没有生成测试的结果，不知道是不是在运行gui文件之前，我还需要进行一些什么操作呢？
![image](https://user-images.githubusercontent.com/55180640/167290130-f806c618-2c1d-4c80-9dc0-c1dabec986bf.png)
![image](https://user-images.githubusercontent.com/55180640/167290222-e3382b08-7597-4447-99aa-c16392414a7f.png)

**Comment by Wenretium** [comment]
> 直接进行测试，demo_files/下面并没有生成result文件夹，当我新建result文件夹之后，并没有生成测试的结果，不知道是不是在运行gui文件之前，我还需要进行一些什么操作呢？ ![image](https://user-images.githubusercontent.com/55180640/167290130-f806c618-2c1d-4c80-9dc0-c1dabec986bf.png) ![image](https://user-images.githubusercontent.com/55180640/167290222-e3382b08-7597-4447-99aa-c16392414a7f.png)

不需要进行额外的操作，您点击左侧的一列按钮后，仍然没有产生结果图像吗？程序终端有输出报错吗？

**Comment by huahuabai** [comment]
> > 直接进行测试，demo_files/下面并没有生成result文件夹，当我新建result文件夹之后，并没有生成测试的结果，不知道是不是在运行gui文件之前，我还需要进行一些什么操作呢？ ![image](https://user-images.githubusercontent.com/55180640/167290130-f806c618-2c1d-4c80-9dc0-c1dabec986bf.png) ![image](https://user-images.githubusercontent.com/55180640/167290222-e3382b08-7597-4447-99aa-c16392414a7f.png)
> 
> 不需要进行额外的操作，您点击左侧的一列按钮后，仍然没有产生结果图像吗？程序终端有输出报错吗？
您好，我更改了demo的测试文件，直接指定了一系列路径，写了主函数，直接调用，这样运行测试脚本是没有问题的，会直接生成测试结果在Result文件下面，这样再运行此文件就没有问题了，非常感谢您的回复。
