### ISSUE TITLE
关于测试文件

### ISSUE THREAD

**Issue by huahuabai** [Wenretium/CIPGAN#2]
您好，感谢您的开源，当按照您给的三种方式进行训练完成后，生成latest_net_D_A.pth   latest_net_D_B.pth   latest_net_G_B.pth latest_net_G_A.pth分别指的是什么呢，我测试的时候应该修改哪个文件为latest_net_G.pth呢，希望能得到您的回复，非常感谢！
![image](https://user-images.githubusercontent.com/55180640/167288832-ee1939d2-1413-4cfa-b702-14e6ecf8a95d.png)

**Comment by Wenretium** [comment]
您好！训练数据集包含trainA和trainB两个文件夹，路径下分别为A域和B域的图像（这里A是真实图像，B是中国画风格图像）。latest_net_G_A.pth是A到B的生成器，latest_net_G_B.pth是B到A的生成器，D_A是对假B图的判别器，D_B是对假A图的判别器。
在测试时，将latest_net_G_A.pth改为latest_net_G.pth，就能将testA下的图像从A域转到B域。

**Comment by huahuabai** [comment]
> 

感谢您的回复，我理解了

**Comment by huahuabai** [comment]
> 您好！训练数据集包含trainA和trainB两个文件夹，路径下分别为A域和B域的图像（这里A是真实图像，B是中国画风格图像）。latest_net_G_A.pth是A到B的生成器，latest_net_G_B.pth是B到A的生成器，D_A是对假B图的判别器，D_B是对假A图的判别器。 在测试时，将latest_net_G_A.pth改为latest_net_G.pth，就能将testA下的图像从A域转到B域。

还有最后一个问题，请问您的数据集都是通过自己搜集得到的吗？
