### ISSUE TITLE
关于测试的问题

### ISSUE THREAD

**Issue by Dracilem** [Wenretium/CIPGAN#3]
作者您好，非常感谢您的开源，但是在我测试的时候遇到了一些问题，如果您有空，希望您能指点一下。

1. 测试的时候报错, no parameter name "attention_thresh" in single_dataset.py line 39，这里我将attention_thresh改为self_attention_thresh之后就没有报错，但我也不知道这样改会不会影响模型。
![image](https://user-images.githubusercontent.com/75916498/198280139-f98c3237-94e7-4f8e-afa7-addd976745de.png)

2. RuntimeError: The size of tensor a (256) must match the size of tensor b (512) at non-singleton dimension 3 
这个问题出现在使用attention时，networks.py报的错，我暂时还没有找到原因，这个问题使用 --preprocess none可以解决
![image](https://user-images.githubusercontent.com/75916498/198280631-6ab0105b-f288-4d7a-a9e9-5f20ca9d491a.png)

3. 与问题二相同的RuntimeError, 但是使用了 --preprocess none 应该是图片没有结果预处理，长宽不标准导致的。
<img width="533" alt="8c77c96427cb1012b665d184f64841a" src="https://user-images.githubusercontent.com/75916498/198281093-53bb3e86-e4a4-47c0-80e6-41444dad6fd4.png">

**Comment by Wenretium** [comment]
您好！首先不好意思，我当时上传这个项目时没有把代码完善，直接运行test.py可能导致问题（可能是我修改了部分代码，导致某些地方的代码不适配了）。您可以先用`python gui.py`来运行我写的图形化demo，体验下算法效果，或者运行有问题也欢迎找我反馈。我这几天再整理下代码，再回复您后续 :D

**Comment by Wenretium** [comment]
您好！我已经重新整理了代码，您提出的bug也修正了（顺便谢谢您指出错误）。您可以重新clone一下，然后按照readme里面新的测试指令运行。有任何问题欢迎来找我讨论！

**Comment by Dracilem** [comment]
作者您好，我试了一下，暂时没有BUG啦 非常感谢您的回复！
