### ISSUE TITLE
关于代码和poster中结构创新中的问题

### ISSUE THREAD

**Issue by Beyangs** [Wenretium/CIPGAN#5]
你好！感谢你的开源，以下是我的问题，麻烦解答
1.在cycle_gan_mode.py的forward函数中有这一行代码,请问有什么含义，为什么这样做呢
self.map_fake_A = torch.ones([self.fake_A.shape[0],1,self.fake_A.shape[2],self.fake_A.shape[3]])
2.在poster中提到的intensity map和self-attention map是一样的吗，都是指getMap得到的map吗？

**Comment by Wenretium** [comment]
你好！
1. 我在生成器设计中将G_A设置为必须有map输入项，因此在计算B域的重建损失时
```
self.rec_B = self.netG_A(self.fake_A, self.map_fake_A)  # G_A(G_B(B))
```
也需要输入一个map项。此处定义一个与self.fake_A的batchsize、形状相同，通道数为1，值全为1的tensor，意思是取图像全部信息作为map。

2. 是的。完成项目时表述不准确，抱歉引起误解，所有map都指getMap函数的输出结果。
