### ISSUE TITLE
RuntimeError: Error(s) in loading state_dict for ResnetGenerator:         Missing key(s) in state_dict: "conv1_map.weight", "conv1_map.bias", "conv2_map.weight", "conv2_map.bias". 

### ISSUE THREAD

**Issue by ysm2000** [Wenretium/CIPGAN#8]
当我用自己的数据集训练完之后，加载test模型就会报这个错：
RuntimeError: Error(s) in loading state_dict for ResnetGenerator:
        Missing key(s) in state_dict: "conv1_map.weight", "conv1_map.bias", "conv2_map.weight", "conv2_map.bias".

**Comment by Wenretium** [comment]
检查一下你训练和加载模型时的指令是否一致，看起来你运行train.py时没有使用--self_attention指令，而运行test.py时又使用了--self_attention，就会报错缺少相关的map模块，因为训练时模型本身就没有定义这个模块。
